name: Build and Test

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches: [main, early-access]
  push:
    branches: [main, early-access]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NODE_VERSION: 22
  CACHE_KEY: "${{ github.ref }}-${{ github.run_id }}-${{ github.run_attempt }}"

jobs:
  test:
    name: Build Package
    runs-on:
      labels: ubuntu-22.04-2cpu-8ram-75ssd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with npm caching
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build auth0-server-js
        run: npm run build -w @auth0/auth0-server-js

      - name: Build auth0-fastify
        run: npm run build -w @auth0/auth0-fastify

      - name: Test auth0-server-js
        run: npm run test:ci -w @auth0/auth0-server-js

      - name: Test auth0-fastify
        run: npm run test:ci -w @auth0/auth0-fastify

  lint:
    name: Lint
    runs-on:
      labels: ubuntu-22.04-2cpu-8ram-75ssd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with npm caching
        uses: actions/setup-node@v4
        with:
          node-version: 22
    
      - name: Install dependencies
        run: npm install

      - name: Run @auth0/auth0-server-js
        run: npm run lint -w @auth0/auth0-server-js
  
      - name: Lint @auth0/auth0-fastify
        run: npm run lint -w @auth0/auth0-fastify